APP = $(notdir $(CURDIR))

OTHER_SOURCES = $(NEURON_DIR)/neuron/models/neuron_model_lif_impl.c
NEURON_IMPL_H = $(EXTRA_SRC_DIR)/my_models/implementations/my_neuron_impl_semd.h
SYNAPSE_DYNAMICS = $(NEURON_DIR)/neuron/plasticity/synapse_dynamics_static_impl.c

include ../extra.mk
