APP = $(notdir $(CURDIR))

OTHER_SOURCES = $(NEURON_DIR)/neuron/models/neuron_model_lif_impl.c
NEURON_IMPL_H = $(EXTRA_SRC_DIR)/my_models/implementations/my_neuron_impl_semd.h

include ../extra_neuron.mk
