APP = $(notdir $(CURDIR))
BUILD_DIR = build/ 
 
SYNAPSE_DYNAMICS = $(NEURON_DIR)/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
TIMING_DEPENDENCE = $(EXTRA_SRC_DIR)/my_models/plasticity/stdp/timing_dependence/my_timing_impl.c
TIMING_DEPENDENCE_H = $(EXTRA_SRC_DIR)/my_models/plasticity/stdp/timing_dependence/my_timing_impl.h
WEIGHT_DEPENDENCE = $(EXTRA_SRC_DIR)/my_models/plasticity/stdp/weight_dependence/my_weight_impl.c
WEIGHT_DEPENDENCE_H = $(EXTRA_SRC_DIR)/my_models/plasticity/stdp/weight_dependence/my_weight_impl.h

include ../extra_synapse.mk
