APP = $(notdir $(CURDIR))

NEURON_IMPL_H = $(EXTRA_SRC_DIR)/my_models/implementations/recording_neuron_impl.h
SYNAPSE_DYNAMICS = $(NEURON_DIR)/neuron/plasticity/synapse_dynamics_static_impl.c
NEURON_MAIN = $(NEURON_DIR)/neuron/neuron2.c

include ../extra.mk
