# THIS FILE WAS USED IN AN OLDER MAKE STYLE
# Make now has to convert c files before building
# SEE https://spinnakermanchester.github.io/latest/Makefiles.html
$(error inclusion of sPyNNaker8NewModelTemplate/c_models/makefiles/Makefile.common)
