# THIS FILE IS A STUB FOR A RENAMED VERSION
# IT IS KEPT FOR BACKWARD COMPATIBILITY ONLY
$(warning inclusion of Makefile.common instead of extra.mk)
include $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/extra.mk
