APP = $(notdir $(CURDIR))
BUILD_DIR = build/

NEURON_IMPL_H = $(EXTRA_SRC_DIR)/my_models/implementations/my_full_neuron_impl.h
SYNAPSE_DYNAMICS = $(SOURCE_DIR)/neuron/plasticity/synapse_dynamics_static_impl.c

include ../common_custom.mk
